name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - la-divino-sabor # Roda sempre que houver uma atualização na branch 'la-divino-sabor'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"